### ISSUE TITLE
CentOS 7 / Amazon Linux 2

### ISSUE THREAD

**Issue by andrewm659** [olegzhr/altprobe#1]
Any chance you can get this working w/ either of the 2 OS'es mentioned in the title?

**Comment by andrewm659** [comment]
I was able to get the packages installed.  However the actual code needs to change.

`

    #!/bin/bash

    #load technical project data for Alertflex collector
    source ./env.sh

    CURRENT_PATH=`pwd`
    if [ $INSTALL_PATH != $CURRENT_PATH ]
    then
	    echo "Please change install directory"
	    exit 0
    fi

    echo "*** Installation alertflex collector started***"
    sudo yum install https://forensics.cert.org/cert-forensics-tools-release-el7.rpm -y
    sudo yum install epel-release -y
    sudo yum -y install pcre pcre2 libc6-dev libnspr4-dev autoconf automake libtool libpcap-dev libnet-devel libyaml libyaml-dev zlib zlib-devel libcap-ng-dev libcap-ng perl-File-LibMagic.x86_64 file-libs libjansson-dev libjansson4 libdaemon-devel GeoIP.x86_64 libgeoip-dev geoip-bin boot-filesystem boost-thread libmicrohttpd logrotate https://forge.fi-ware.org/frs/download.php/1502/contextBroker-0.15.0-1.x86_64.rpm make autoconf-archive m4 python2-pkgconfig.noarch git openssl-libs openssl-devel redis-server curl python2-simplejson.x86_64 sudo ldconfig

    echo "*** installation hiredis***"
    sudo yum install hiredis hiredis-devel -y

    echo "*** installation activemq ***"
    sudo yum -y install httpd-devel libapreq2-devel apr-util apr-util-devel java-1.8.0-openjdk activemq-cpp.x86_64 activemq-cpp-devel.x86_64

    echo "*** installation altprobe ***"
    cd ~/Altprobe/src
    sudo make
    sudo make install
    sudo mkdir -pv /etc/alertflex/

    if [ $AMQ_PWD != none ]
    then
	    sudo cp ./etc/alertflex-ssl.yaml /etc/alertflex/alertflex.yaml
	    sudo sed -i "s/_amq_pwd/$AMQ_PWD/g" /etc/alertflex/alertflex.yaml
	    sudo sed -i "s/_amq_host/$AMQ_BROKER/g" /etc/alertflex/alertflex.yaml
    fi

    sudo sed -i "s/_node_id/$NODE_ID/g" /etc/alertflex/alertflex.yaml
    sudo chmod go-rwx /etc/alertflex/alertflex.yaml
    sudo cp -v ./configs/rc.local /etc/

    cd ..

    if [ $INSTALL_SURICATA == yes ]
    then
	    echo "*** installation suricata ***"
	    sudo yum -y install gcc libpcap-devel pcre-devel libyaml-devel file-devel zlib-devel jansson-devel nss-devel libcap-ng-devel libnet-devel tar make libnetfilter_queue-devel lua-devel gcc libpcap-devel pcre-devel libyaml-devel file-devel mariadb-devel GeoIP-devel zlib-devel jansson-devel nss-devel libcap-ng-devel libnet-devel libnetfilter_queue-devel ethtool libpcap libpcap-devel file-devel libcap-ng-devel suricata

	sudo sed -i "s/_monitoring_interface/$INTERFACE/g" /etc/suricata/suricata.yaml
	if [ $EXTRACT_FILES == yes ]
	then
		sudo cp ./configs/suricata-files.yaml /etc/suricata/suricata.yaml
		sudo cp ./configs/files.rules /etc/suricata/rules
	else
		sudo cp ./configs/suricata.yaml /etc/suricata/
	fi
    fi

    if [ $INSTALL_WAZUH == yes ]
    then

	echo "*** installation OSSEC/WAZUH server ***"
	sudo apt-get update
	sudo apt-get -y install curl apt-transport-https lsb-release
	curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | sudo apt-key add -
	echo "deb https://packages.wazuh.com/3.x/apt/ stable main" | sudo tee -a /etc/apt/sources.list.d/wazuh.list
	sudo apt-get update
	sudo apt-get -y install wazuh-manager

	echo "*** installation  Wazuh API***"
	curl -sL https://deb.nodesource.com/setup_6.x | sudo bash -
	sudo apt-get -y install nodejs
	sudo apt-get -y install wazuh-api
	sudo sed -i "s/_wazuh_user/$WAZUH_USER/g" /etc/alertflex/alertflex.yaml
	sudo sed -i "s/_wazuh_pwd/$WAZUH_PWD/g" /etc/alertflex/alertflex.yaml

	echo "*** installation filebeat***"
	sudo apt-get update
	curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.2.2-amd64.deb
	sudo dpkg -i filebeat-6.2.2-amd64.deb
	sudo update-rc.d filebeat defaults 95 10
	sudo cp ./configs/filebeat.yml /etc/filebeat/

    fi
    cd ..
`

**Comment by olegzhr** [comment]
Hi,
for compile altprobe for centos 7

1) please install the next packages
sudo yum install boost-devel libyaml-devel mod_geoip GeoIP GeoIP-devel GeoIP-data zlib-devel

2) make the next changes in files: Altprobe/src/nbproject/configurations.xml and Altprobe/src/nbproject/Makefile-Debug.mk
change the strings "/usr/local/include/activemq-cpp-3.10.0/" to "/usr/include/activemq-cpp-3.9.3"
"/usr/include/apr-1.0/" to "/usr/include/apr-1/"
"usr/local/include/hiredis" to "usr/include/hiredis"

Unfortunately, at the moment I haven't time for testing altprobe for centos, but it's in my plans.
if you are going to continue installation of altprobe for centos 7, please share your results here
Thanks

**Comment by olegzhr** [comment]
Install script for centos 7 was added.
Instead of centos official package of suricata 4.0.5 a suricata 4.0.3 is used due to altprobe wasn't tested with version 4.0.5.
