### ISSUE TITLE
Alertflex not working after installation [CNODE]

### ISSUE THREAD

**Issue by HassanShehata** [olegzhr/altprobe#3]
I have ubuntu 18.04, 4 GB RAM, 2 CPU. I followed the installation instructions in the documentation. then rebooted. The GUI is up on port 443 when I click alertflex tab it gives me 404

**Comment by olegzhr** [comment]
Hi, sorry, the management console is not available at this moment, because a new soft update is supposed. The release with new mc will be at the end of this January.

**Comment by MarkDevelo** [comment]
Looking forward to new release...Also a discord server would be nice...

**Comment by olegzhr** [comment]
Hi, sw update done, you can try to install the new release
Discord server for alertflex is available via link -  https://discord.gg/wDSz7rDMWv

**Comment by MarkDevelo** [comment]
> I have ubuntu 18.04, 4 GB RAM, 2 CPU. I followed the installation instructions in the documentation. then rebooted. The GUI is up on port 443 when I click alertflex tab it gives me 404

Hi HassanShehata, have you been able to fix the issue ? Im having the same problem but with the nginx 502 Bad Gateway, only when i launch it via Payara, i get the 404.

**Comment by olegzhr** [comment]
Hi, I've written down some notes, how to troubleshoot an installation of Cnode, please see this info in Discord chat.

**Comment by olegzhr** [comment]
work after installation
